"""
agat_hybrid_ce.py — Attribution-Guided Adversarial Training (AGAT Hybrid CE)
==============================================================================
Standalone implementation of the AGAT Hybrid CE method from:

  "Explainable Adversarial Training for IoT Network Traffic Classification"
  Mohamed Massaoudi, Maymouna Ez Eddin, Katherine R. Davis
  Texas A&M University / Tarleton State University

AGAT Hybrid CE training objective:
    loss = 0.30 * CE(f(x), y)
         + 0.50 * CE(f(x_agat), y)
         + 0.20 * CE(f(x_pgd),  y)

where x_agat is generated by the momentum-attribution AGAT attack and
x_pgd by standard PGD, both with class-weighted CE and the IoT
perturbability mask.

Requirements: torch >= 2.0, numpy, pandas, scikit-learn, xgboost, scipy
Dataset:      RT-IoT2022 CSV  (https://archive.ics.uci.edu/dataset/942)
              Place at: data/RT_IOT/RT_IOT2022.csv
"""

import os
import time
import json
import warnings
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (accuracy_score, f1_score, roc_auc_score,
                              classification_report)
from scipy.stats import chi2 as scipy_chi2

warnings.filterwarnings("ignore")

# ── Device ────────────────────────────────────────────────────────────────────
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")

# ── Reproducibility ───────────────────────────────────────────────────────────
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)

# ── Hyperparameters ───────────────────────────────────────────────────────────
EPOCHS      = 30          # primary training epochs
BATCH       = 1024        # mini-batch size
EPS         = 0.1         # L-inf perturbation budget
ALPHA_TRAIN = 0.04        # PGD step size during training (eps/2.5)
T_TRAIN     = 7           # PGD inner-loop steps during training
T_EVAL      = 10          # PGD steps at evaluation
MOMENTUM_ATTR = 0.85      # EMA momentum for attribution smoothing
N_PER_CLASS   = 2000      # stratified samples per class

# ── RT-IoT2022 perturbability mask (83 features) ──────────────────────────────
# 0.0 = protocol-fixed (TCP flags, proto, service)
# 0.5 = partially constrained (ports, counts, durations, header sizes)
# 1.0 = freely perturbable (IAT/payload stats, rates, bulk, active/idle)
PERTURBABLE_IOT = np.array([
    0.5, 0.5, 0.0, 0.0,            # 0-3:  ports, proto, service
    0.5, 0.5, 0.5, 0.5, 0.5,       # 4-8:  flow_duration, pkt counts
    1.0, 1.0, 1.0, 1.0,            # 9-12: pkt/sec rates, down_up_ratio
    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, # 13-18: header sizes
    0.0, 0.0, 0.0, 0.0, 0.0,       # 19-23: FIN/SYN/RST/PSH flags
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # 24-29: ACK/URG/CWR/ECE + boundary
    1.0, 1.0, 1.0, 1.0, 1.0,       # 30-34: fwd payload stats
    1.0, 1.0, 1.0, 1.0, 1.0,       # 35-39: bwd payload stats
    1.0, 1.0, 1.0, 1.0, 1.0,       # 40-44: flow payload stats
    1.0, 1.0, 1.0, 1.0, 1.0,       # 45-49: fwd IAT stats
    1.0, 1.0, 1.0, 1.0, 1.0,       # 50-54: bwd IAT stats
    1.0, 1.0, 1.0, 1.0, 1.0,       # 55-59: flow IAT stats
    1.0,                            # 60:   payload_bytes_per_second
    0.5, 0.5, 0.5, 0.5,            # 61-64: subflow pkts/bytes
    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, # 65-70: bulk bytes/pkts/rate
    1.0, 1.0, 1.0, 1.0, 1.0,       # 71-75: active stats
    1.0, 1.0, 1.0, 1.0, 1.0,       # 76-80: idle stats
    0.5, 0.5, 0.5,                  # 81-83: window sizes
], dtype=np.float32)[:83]


# ══════════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ══════════════════════════════════════════════════════════════════════════════

def stratified_subsample(X, y, n_per_class=N_PER_CLASS, seed=SEED):
    """Return a class-balanced subsample of (X, y)."""
    rng = np.random.default_rng(seed)
    idxs = []
    for cls in np.unique(y):
        pool = np.where(y == cls)[0]
        idxs.append(rng.choice(pool, min(n_per_class, len(pool)), replace=False))
    idx = np.concatenate(idxs)
    rng.shuffle(idx)
    return X[idx], y[idx]


def load_rt_iot(data_root="data"):
    """
    Load and preprocess RT-IoT2022.
    Returns (X_train, X_test, y_train, y_test, class_names, feat_mask).
    """
    csv_path = os.path.join(data_root, "RT_IOT", "RT_IOT2022.csv")
    df = pd.read_csv(csv_path)

    y_col = "Attack_type"
    y_raw = df[y_col].astype(str).values
    X_raw = df.drop(columns=[y_col, "Unnamed: 0"], errors="ignore")

    # Encode string columns
    for col in X_raw.select_dtypes("object").columns:
        X_raw[col] = LabelEncoder().fit_transform(X_raw[col].astype(str))

    X = X_raw.fillna(0).values.astype(np.float32)

    # Keep top-5 classes, label-encode
    le = LabelEncoder()
    y_enc = le.fit_transform(y_raw)
    class_names = list(le.classes_)

    # Stratified 2000/class balanced sample
    X, y_enc = stratified_subsample(X, y_enc, n_per_class=N_PER_CLASS)

    # Shuffle
    perm = np.random.permutation(len(X))
    X, y_enc = X[perm], y_enc[perm]

    # 80/20 split
    sc = StandardScaler()
    split = int(0.8 * len(X))
    X_tr = sc.fit_transform(X[:split]).astype(np.float32)
    X_te = sc.transform(X[split:]).astype(np.float32)
    y_tr, y_te = y_enc[:split].astype(np.int64), y_enc[split:].astype(np.int64)

    # Trim perturbability mask to actual feature count
    feat_mask = PERTURBABLE_IOT[:X_tr.shape[1]]

    print(f"  RT-IoT2022: {X_tr.shape[0]} train / {X_te.shape[0]} test  "
          f"| {X_tr.shape[1]} features  | {len(class_names)} classes")
    print(f"  Classes: {class_names}")
    return X_tr, X_te, y_tr, y_te, class_names, feat_mask


# ══════════════════════════════════════════════════════════════════════════════
# MODEL ARCHITECTURE
# ══════════════════════════════════════════════════════════════════════════════

class ResBlock(nn.Module):
    """Two-layer residual block with BatchNorm."""
    def __init__(self, dim: int):
        super().__init__()
        self.block = nn.Sequential(
            nn.Linear(dim, dim), nn.BatchNorm1d(dim), nn.ReLU(),
            nn.Linear(dim, dim), nn.BatchNorm1d(dim),
        )
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.relu(x + self.block(x))


class BaseDNN(nn.Module):
    """
    Residual MLP: Input → 512 → 256 → 128 → 64 → C classes.
    Used for all AGAT/TRADES variants.
    """
    def __init__(self, in_features: int, n_classes: int):
        super().__init__()
        self.proj = nn.Sequential(
            nn.Linear(in_features, 512), nn.BatchNorm1d(512), nn.ReLU(),
            nn.Dropout(0.25),
        )
        self.res1 = ResBlock(512)
        self.mid1 = nn.Sequential(
            nn.Linear(512, 256), nn.BatchNorm1d(256), nn.ReLU(), nn.Dropout(0.25),
        )
        self.res2 = ResBlock(256)
        self.mid2 = nn.Sequential(
            nn.Linear(256, 128), nn.BatchNorm1d(128), nn.ReLU(), nn.Dropout(0.25),
        )
        self.res3 = ResBlock(128)
        self.head = nn.Sequential(
            nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(64, n_classes),
        )

    def forward(self, x):
        h = self.proj(x)
        h = self.res1(h)
        h = self.mid1(h)
        h = self.res2(h)
        h = self.mid2(h)
        h = self.res3(h)
        return self.head(h)


# ══════════════════════════════════════════════════════════════════════════════
# ADVERSARIAL ATTACKS
# ══════════════════════════════════════════════════════════════════════════════

def _ce_loss(model, x, y, class_w=None):
    """Weighted cross-entropy helper."""
    return F.cross_entropy(model(x), y, weight=class_w)


def fgsm(model, x, y, eps, class_w=None):
    """Fast Gradient Sign Method (single step)."""
    xr = x.clone().detach().requires_grad_(True)
    _ce_loss(model, xr, y, class_w).backward()
    model.zero_grad()
    return (x + eps * xr.grad.sign()).detach()


def pgd(model, x, y, eps, alpha, iters, class_w=None):
    """Projected Gradient Descent adversarial attack."""
    xa = x.clone().detach() + torch.zeros_like(x).uniform_(-eps / 2, eps / 2)
    for _ in range(iters):
        xa.requires_grad_(True)
        _ce_loss(model, xa, y, class_w).backward()
        model.zero_grad()
        xa = (xa + alpha * xa.grad.sign()).detach()
        xa = torch.max(torch.min(xa, x + eps), x - eps).detach()
    return xa


def agat_attack(model, x, y, eps, alpha, iters,
                feat_mask=None, momentum=MOMENTUM_ATTR, class_w=None):
    """
    AGAT attack: Momentum-attribution-guided PGD with L1-normalised
    budget redistribution.

    Algorithm:
      1. EMA-smooth the input×gradient attribution over PGD steps.
      2. L1-normalise: weights sum to 1 (pure redistribution).
      3. Step size = alpha * F_dim * w * sign(grad)  →  same mean magnitude as PGD.
      4. Project back onto the L-inf epsilon-ball.
    """
    xa = x.clone().detach() + torch.zeros_like(x).uniform_(-eps / 2, eps / 2)
    F_dim = x.shape[1]
    mask_t = torch.FloatTensor(feat_mask).to(x.device) if feat_mask is not None else None
    phi_ema = None

    for _ in range(iters):
        xa = xa.clone().detach().requires_grad_(True)
        _ce_loss(model, xa, y, class_w).backward()
        model.zero_grad()

        with torch.no_grad():
            grad = xa.grad.detach()
            phi  = (xa.detach() * grad).abs()          # input × gradient

            if mask_t is not None:
                phi = phi * mask_t.unsqueeze(0)         # zero non-perturbable dims

            # Momentum EMA
            phi_ema = phi if phi_ema is None else (
                momentum * phi_ema + (1.0 - momentum) * phi
            )

            # L1 normalisation (redistribute budget, same total magnitude as PGD)
            w    = phi_ema / (phi_ema.sum(dim=1, keepdim=True) + 1e-8)
            step = alpha * F_dim * w * grad.sign()

            xa = torch.max(torch.min(xa.detach() + step, x + eps), x - eps)

    return xa.detach()


def bipgd(model, x, y, eps, alpha, iters, class_w=None):
    """
    Boundary-Initialized PGD (BI-PGD): starts from a random point
    on the boundary of the L-inf epsilon-ball, then runs standard PGD.
    Stress-tests against gradient masking.
    """
    n  = torch.randn_like(x)
    xa = torch.max(torch.min(x + eps * n.sign(), x + eps), x - eps).detach()
    for _ in range(iters):
        xa.requires_grad_(True)
        _ce_loss(model, xa, y, class_w).backward()
        model.zero_grad()
        xa = (xa + alpha * xa.grad.sign()).detach()
        xa = torch.max(torch.min(xa, x + eps), x - eps).detach()
    return xa


def random_agat(model, x, y, eps, alpha, iters, feat_mask=None, class_w=None):
    """
    Random-AGAT ablation: replaces attribution weights with Dirichlet-random
    weights. Used to isolate attribution-specific contribution vs. any
    non-uniform budget redistribution effect.
    """
    xa = x.clone().detach() + torch.zeros_like(x).uniform_(-eps / 2, eps / 2)
    F_dim   = x.shape[1]
    mask_t  = torch.FloatTensor(feat_mask).to(x.device) if feat_mask is not None else None

    for _ in range(iters):
        xa = xa.clone().detach().requires_grad_(True)
        _ce_loss(model, xa, y, class_w).backward()
        model.zero_grad()

        with torch.no_grad():
            grad   = xa.grad.detach()
            w_rand = torch.from_numpy(
                np.random.dirichlet(np.ones(F_dim), x.shape[0]).astype(np.float32)
            ).to(x.device)
            if mask_t is not None:
                w_rand = w_rand * mask_t.unsqueeze(0)
                w_rand = w_rand / (w_rand.sum(dim=1, keepdim=True) + 1e-8)
            step = alpha * F_dim * w_rand * grad.sign()
            xa   = torch.max(torch.min(xa.detach() + step, x + eps), x - eps)

    return xa.detach()


# ══════════════════════════════════════════════════════════════════════════════
# CLASS WEIGHTS (inverse-frequency)
# ══════════════════════════════════════════════════════════════════════════════

def compute_class_weights(y_train, device=DEVICE):
    """Inverse-frequency class weights for imbalanced training data."""
    counts = np.bincount(y_train)
    w = 1.0 / (counts + 1e-6)
    w = w / w.sum() * len(counts)
    return torch.FloatTensor(w).to(device)


# ══════════════════════════════════════════════════════════════════════════════
# TRAINING — AGAT HYBRID CE
# ══════════════════════════════════════════════════════════════════════════════

def train_agat_hybrid_ce(
    model, X_tr, y_tr,
    eps=EPS, alpha=ALPHA_TRAIN, iters=T_TRAIN,
    epochs=EPOCHS, feat_mask=None,
    device=DEVICE, verbose=True,
):
    """
    Train AGAT Hybrid CE.

    Loss = 0.30 * CE(f(x), y)               [clean]
         + 0.50 * CE(f(x_agat), y)          [AGAT adversarial, attribution-guided]
         + 0.20 * CE(f(x_pgd),  y)          [PGD adversarial, generic L-inf]

    All CE terms use inverse-frequency class weights.

    Args:
        model      : BaseDNN (or any nn.Module with appropriate in/out dims)
        X_tr, y_tr : Training tensors
        eps        : L-inf perturbation budget (default 0.1)
        alpha      : PGD step size (default 0.04 = eps/2.5)
        iters      : PGD inner-loop steps (default 7)
        epochs     : Number of training epochs (default 30)
        feat_mask  : Per-feature perturbability mask array (83-dim for RT-IoT2022)
        device     : torch.device
        verbose    : Print epoch-level progress

    Returns:
        (clean_loss_history, adv_loss_history)
    """
    model = model.to(device)
    X_tr_d = X_tr.to(device)
    y_tr_d = y_tr.to(device)

    class_w = compute_class_weights(y_tr.numpy(), device)
    opt     = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=5e-4)
    sched   = optim.lr_scheduler.CosineAnnealingWarmRestarts(opt, T_0=10, T_mult=2)
    loader  = DataLoader(TensorDataset(X_tr_d, y_tr_d), batch_size=BATCH, shuffle=True)

    hist_clean, hist_adv = [], []

    for ep in range(1, epochs + 1):
        model.train()
        lc_sum = la_sum = 0.0

        for xb, yb in loader:
            opt.zero_grad()

            # Clean loss
            lc = F.cross_entropy(model(xb), yb, weight=class_w)

            # AGAT adversarial examples (momentum attribution, L1-normalised)
            xa_agat = agat_attack(
                model, xb, yb, eps, alpha, iters,
                feat_mask=feat_mask, class_w=class_w,
            )

            # PGD adversarial examples (standard L-inf PGD)
            xa_pgd = pgd(model, xb, yb, eps, alpha, iters, class_w)

            model.train()
            la_agat = F.cross_entropy(model(xa_agat), yb, weight=class_w)
            la_pgd  = F.cross_entropy(model(xa_pgd),  yb, weight=class_w)

            # AGAT Hybrid CE loss
            loss = 0.30 * lc + 0.50 * la_agat + 0.20 * la_pgd
            loss.backward()
            opt.step()

            lc_sum += lc.item()
            la_sum += la_agat.item()

        sched.step()
        hist_clean.append(lc_sum / len(loader))
        hist_adv.append(la_sum / len(loader))

        if verbose and (ep % 5 == 0 or ep == 1 or ep == epochs):
            print(f"  Epoch {ep:3d}/{epochs}  clean_loss={hist_clean[-1]:.4f}  "
                  f"adv_loss={hist_adv[-1]:.4f}")

    return hist_clean, hist_adv


# ══════════════════════════════════════════════════════════════════════════════
# EVALUATION
# ══════════════════════════════════════════════════════════════════════════════

EVAL_CAP = 1000   # cap evaluation to speed up (use all samples for final eval)


@torch.no_grad()
def evaluate_clean(model, X_te, y_te, device=DEVICE):
    """Accuracy, macro-F1, macro-AUC on clean test set."""
    model.eval()
    Xe = X_te.to(device)
    logits = model(Xe)
    preds  = logits.argmax(1).cpu().numpy()
    y_np   = y_te.numpy()
    n_cls  = len(np.unique(y_np))
    acc    = accuracy_score(y_np, preds)
    f1     = f1_score(y_np, preds, average="macro", zero_division=0)
    try:
        probs = F.softmax(logits, 1).cpu().numpy()
        auc   = roc_auc_score(y_np, probs, multi_class="ovr", average="macro")
    except Exception:
        auc = float("nan")
    return dict(acc=acc, f1=f1, auc=auc)


def _adv_accuracy(attack_fn, model, X_te, y_te, device=DEVICE, cap=EVAL_CAP):
    """Evaluate adversarial accuracy using a given attack function."""
    Xe = X_te[:cap].to(device)
    ye = y_te[:cap].to(device)
    preds_all = []
    for i in range(0, len(Xe), 256):
        model.train()                           # needed for BN in attack backward
        xa = attack_fn(Xe[i:i+256], ye[i:i+256])
        model.eval()
        with torch.no_grad():
            preds_all.append(model(xa).argmax(1).cpu())
    preds = torch.cat(preds_all).numpy()
    return accuracy_score(ye.cpu().numpy()[:len(preds)], preds)


def evaluate_adversarial(model, X_te, y_te,
                          eps=EPS, feat_mask=None,
                          device=DEVICE, cap=EVAL_CAP):
    """
    Full adversarial evaluation suite:
      FGSM, PGD-10, PGD-20, PGD-50, BI-PGD-10, Rand-AGAT-10
    """
    alpha10 = eps / 10.0
    alpha20 = eps / 20.0
    alpha50 = eps / 50.0

    return {
        "fgsm":      _adv_accuracy(
                         lambda x, y: fgsm(model, x, y, eps),
                         model, X_te, y_te, device, cap),
        "pgd_10":    _adv_accuracy(
                         lambda x, y: pgd(model, x, y, eps, alpha10, 10),
                         model, X_te, y_te, device, cap),
        "pgd_20":    _adv_accuracy(
                         lambda x, y: pgd(model, x, y, eps, alpha20, 20),
                         model, X_te, y_te, device, cap),
        "pgd_50":    _adv_accuracy(
                         lambda x, y: pgd(model, x, y, eps, alpha50, 50),
                         model, X_te, y_te, device, cap),
        "bi_pgd":    _adv_accuracy(
                         lambda x, y: bipgd(model, x, y, eps, alpha10, 10),
                         model, X_te, y_te, device, cap),
        "rand_agat": _adv_accuracy(
                         lambda x, y: random_agat(model, x, y, eps, alpha10, 10,
                                                   feat_mask=feat_mask),
                         model, X_te, y_te, device, cap),
    }


def per_class_f1(model, X_te, y_te, class_names,
                 eps=EPS, device=DEVICE, cap=EVAL_CAP):
    """Per-class F1 under PGD-10."""
    alpha = eps / 10.0
    Xe = X_te[:cap].to(device)
    ye = y_te[:cap].to(device)
    preds_all = []
    for i in range(0, len(Xe), 256):
        model.train()
        xa = pgd(model, Xe[i:i+256], ye[i:i+256], eps, alpha, 10)
        model.eval()
        with torch.no_grad():
            preds_all.append(model(xa).argmax(1).cpu())
    preds = torch.cat(preds_all).numpy()
    y_np  = ye.cpu().numpy()[:len(preds)]
    rpt   = classification_report(y_np, preds, output_dict=True, zero_division=0)
    return {cn: rpt.get(str(i), {}).get("f1-score", 0.0)
            for i, cn in enumerate(class_names)}


# ══════════════════════════════════════════════════════════════════════════════
# STATISTICAL TESTS
# ══════════════════════════════════════════════════════════════════════════════

def mcnemar_test(y_true, preds_a, preds_b):
    """
    McNemar's test between two classifiers.
    Returns (p_value, chi2_statistic).
    """
    a_right = np.array(preds_a) == np.array(y_true)
    b_right = np.array(preds_b) == np.array(y_true)
    b = np.sum(a_right  & ~b_right)
    c = np.sum(~a_right &  b_right)
    if b + c == 0:
        return 1.0, 0.0
    stat  = (abs(b - c) - 1.0) ** 2 / (b + c)
    p_val = 1.0 - scipy_chi2.cdf(stat, df=1)
    return float(p_val), float(stat)


def _adv_preds(model, X_te, y_te, eps=EPS, device=DEVICE, cap=EVAL_CAP):
    """Return adversarial predictions under PGD-10 (for McNemar test)."""
    alpha = eps / 10.0
    Xe = X_te[:cap].to(device)
    ye = y_te[:cap].to(device)
    preds = []
    for i in range(0, len(Xe), 256):
        model.train()
        xa = pgd(model, Xe[i:i+256], ye[i:i+256], eps, alpha, 10)
        model.eval()
        with torch.no_grad():
            preds.append(model(xa).argmax(1).cpu())
    return torch.cat(preds).numpy(), ye.cpu().numpy()[:sum(p.shape[0] for p in preds)]


# ══════════════════════════════════════════════════════════════════════════════
# MAIN EXPERIMENT
# ══════════════════════════════════════════════════════════════════════════════

def main(data_root="data", results_dir="results", save_json=True):
    """
    Full AGAT Hybrid CE experiment on RT-IoT2022.

    Trains AGAT Hybrid CE and PGD-AT baseline, evaluates both,
    runs McNemar test, prints results table, and optionally saves JSON.
    """
    os.makedirs(results_dir, exist_ok=True)
    t0 = time.time()

    print("=" * 64)
    print("  AGAT Hybrid CE — RT-IoT2022 Experiment")
    print(f"  Device: {DEVICE}  |  Epochs: {EPOCHS}  |  eps={EPS}")
    print("=" * 64)

    # ── 1. Load data ──────────────────────────────────────────────────────────
    print("\n[1] Loading RT-IoT2022...")
    X_tr, X_te, y_tr, y_te, class_names, feat_mask = load_rt_iot(data_root)
    Xt = torch.FloatTensor(X_tr)
    Xe = torch.FloatTensor(X_te)
    yt = torch.LongTensor(y_tr)
    ye = torch.LongTensor(y_te)
    d, c = X_tr.shape[1], len(class_names)

    # ── 2. Train AGAT Hybrid CE ────────────────────────────────────────────────
    print("\n[2] Training AGAT Hybrid CE...")
    model_agat = BaseDNN(d, c)
    train_agat_hybrid_ce(
        model_agat, Xt, yt, eps=EPS, alpha=ALPHA_TRAIN, iters=T_TRAIN,
        epochs=EPOCHS, feat_mask=feat_mask, device=DEVICE, verbose=True,
    )

    # ── 3. Train PGD-AT baseline ───────────────────────────────────────────────
    print("\n[3] Training PGD-AT baseline...")
    model_pgd = BaseDNN(d, c)
    class_w   = compute_class_weights(y_tr, DEVICE)
    opt_pgd   = optim.AdamW(model_pgd.parameters(), lr=1e-3, weight_decay=5e-4)
    sched_pgd = optim.lr_scheduler.CosineAnnealingWarmRestarts(opt_pgd, T_0=10, T_mult=2)
    loader_pgd = DataLoader(TensorDataset(Xt.to(DEVICE), yt.to(DEVICE)),
                            batch_size=BATCH, shuffle=True)
    model_pgd = model_pgd.to(DEVICE)
    for ep in range(1, EPOCHS + 1):
        model_pgd.train()
        for xb, yb in loader_pgd:
            opt_pgd.zero_grad()
            alpha = EPS / max(T_TRAIN / 2.0, 1.0)
            xa    = pgd(model_pgd, xb, yb, EPS, alpha, T_TRAIN, class_w)
            model_pgd.train()
            lc = F.cross_entropy(model_pgd(xb), yb, weight=class_w)
            la = F.cross_entropy(model_pgd(xa), yb, weight=class_w)
            (0.5 * lc + 0.5 * la).backward()
            opt_pgd.step()
        sched_pgd.step()
        if ep % 5 == 0 or ep == EPOCHS:
            print(f"  PGD-AT  epoch {ep:3d}/{EPOCHS}")

    # ── 4. Evaluate ───────────────────────────────────────────────────────────
    print("\n[4] Evaluating...")
    for tag, mdl in [("AGAT Hybrid CE", model_agat), ("PGD-AT", model_pgd)]:
        clean  = evaluate_clean(mdl, Xe, ye, DEVICE)
        adv    = evaluate_adversarial(mdl, Xe, ye, EPS, feat_mask, DEVICE)
        pc_f1  = per_class_f1(mdl, Xe, ye, class_names, EPS, DEVICE)
        print(f"\n  {tag}")
        print(f"    Clean:     acc={clean['acc']*100:.1f}%  f1={clean['f1']:.3f}  "
              f"auc={clean['auc']:.4f}")
        print(f"    FGSM:      {adv['fgsm']*100:.1f}%")
        print(f"    PGD-10:    {adv['pgd_10']*100:.1f}%")
        print(f"    PGD-20:    {adv['pgd_20']*100:.1f}%")
        print(f"    PGD-50:    {adv['pgd_50']*100:.1f}%")
        print(f"    BI-PGD:    {adv['bi_pgd']*100:.1f}%   ← stress-test metric")
        print(f"    Rand-AGAT: {adv['rand_agat']*100:.1f}%")
        print(f"    Per-class F1 (PGD-10):")
        for cn, v in pc_f1.items():
            print(f"      {cn}: {v:.3f}")

    # ── 5. McNemar test ───────────────────────────────────────────────────────
    print("\n[5] McNemar test (AGAT Hybrid CE vs PGD-AT, PGD-10)...")
    preds_agat, y_true = _adv_preds(model_agat, Xe, ye, EPS, DEVICE)
    preds_pgd,  _      = _adv_preds(model_pgd,  Xe, ye, EPS, DEVICE)
    mcn_p, mcn_chi2    = mcnemar_test(y_true, preds_agat, preds_pgd)
    print(f"  chi2={mcn_chi2:.3f}  p={'<0.001' if mcn_p < 0.001 else f'{mcn_p:.4f}'}"
          f"  {'SIGNIFICANT' if mcn_p < 0.05 else 'not significant'}")

    # ── 6. Save results ───────────────────────────────────────────────────────
    if save_json:
        clean_agat = evaluate_clean(model_agat, Xe, ye, DEVICE)
        clean_pgd  = evaluate_clean(model_pgd,  Xe, ye, DEVICE)
        adv_agat   = evaluate_adversarial(model_agat, Xe, ye, EPS, feat_mask, DEVICE)
        adv_pgd    = evaluate_adversarial(model_pgd,  Xe, ye, EPS, feat_mask, DEVICE)
        out = {
            "AGAT Hybrid CE": {
                "clean": {k: round(float(v), 4) for k, v in clean_agat.items()},
                "adv":   {k: round(float(v), 4) for k, v in adv_agat.items()},
            },
            "PGD-AT": {
                "clean": {k: round(float(v), 4) for k, v in clean_pgd.items()},
                "adv":   {k: round(float(v), 4) for k, v in adv_pgd.items()},
            },
            "mcnemar": {"chi2": round(mcn_chi2, 4), "p": round(mcn_p, 6)},
            "class_names": class_names,
            "hyperparameters": {
                "eps": EPS, "alpha_train": ALPHA_TRAIN, "T_train": T_TRAIN,
                "epochs": EPOCHS, "batch": BATCH, "momentum_attr": MOMENTUM_ATTR,
                "n_per_class": N_PER_CLASS, "seed": SEED,
                "loss_weights": {"clean": 0.30, "agat": 0.50, "pgd": 0.20},
            },
        }
        out_path = os.path.join(results_dir, "agat_hybrid_ce_results.json")
        with open(out_path, "w") as f:
            json.dump(out, f, indent=2)
        print(f"\n  Results saved to {out_path}")

    print(f"\n  Total time: {(time.time() - t0) / 60:.1f} min")
    return model_agat, model_pgd


# ══════════════════════════════════════════════════════════════════════════════
# REPRODUCIBILITY UTILITIES
# ══════════════════════════════════════════════════════════════════════════════

def set_seed(seed=SEED):
    """Set all random seeds for reproducibility."""
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def save_model(model, path):
    """Save model state dict."""
    torch.save(model.state_dict(), path)
    print(f"  Saved: {path}")


def load_model(path, in_features, n_classes, device=DEVICE):
    """Load model from state dict."""
    model = BaseDNN(in_features, n_classes).to(device)
    model.load_state_dict(torch.load(path, map_location=device))
    model.eval()
    return model


# ══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="AGAT Hybrid CE — Explainable Adversarial Training for IoT Traffic"
    )
    parser.add_argument("--data",    default="data",    help="Root folder containing RT_IOT/RT_IOT2022.csv")
    parser.add_argument("--results", default="results", help="Output folder for JSON results")
    parser.add_argument("--epochs",  type=int, default=EPOCHS, help="Training epochs")
    parser.add_argument("--seed",    type=int, default=SEED,   help="Random seed")
    parser.add_argument("--eps",     type=float, default=EPS,  help="L-inf epsilon")
    parser.add_argument("--no-json", action="store_true",      help="Skip JSON output")
    args = parser.parse_args()

    EPOCHS = args.epochs
    EPS    = args.eps
    set_seed(args.seed)

    main(data_root=args.data, results_dir=args.results, save_json=not args.no_json)
